### ISSUE TITLE
this._getApp is not a function; [Component] Lifetime Method Error @ components/navBar/navBar#created TypeError: this._getApp is not a function

### ISSUE THREAD

**Issue by Gaoyongxian666** [lingxiaoyi/navigation-bar#25]
thirdScriptError
this._getApp is not a function; [Component] Lifetime Method Error @ components/navBar/navBar#created
TypeError: this._getApp is not a function
    at ye.getSystemInfo (http://127.0.0.1:63328/appservice/components/navBar/navBar.js:146:22)
    at ye.created (http://127.0.0.1:63328/appservice/components/navBar/navBar.js:70:10)
    at r.safeCallback (WAService.js:1:1037423)
    at r.call (WAService.js:1:1037316)
    at Function.x._advancedCreate (WAService.js:1:1136263)
    at r.createComponent (WAService.js:1:1146424)
    at e (WAService.js:1:1179207)
    at e (WAService.js:1:1180502)
    at e.value (WAService.js:1:1204216)
    at x._advancedCreate (WAService.js:1:1134731)

**Comment by lingxiaoyi** [comment]
是不是分包问题

**Comment by Gaoyongxian666** [comment]
我没有分包，就是按照你给的实例做的：1.引入组件2.示例代码

**Comment by Gaoyongxian666** [comment]
感觉方法定义的位置有问题

**Comment by Gaoyongxian666** [comment]
我直接用你git上的代码也是同样的问题

**Comment by lingxiaoyi** [comment]
你导入demo也不行吗?别人用的好好的啊

**Comment by Gaoyongxian666** [comment]
是的，我就是直接导入你github上的demo，不行，一样的错误

**Comment by Gaoyongxian666** [comment]
![2020-04-22_115533](https://user-images.githubusercontent.com/35163802/79938856-466e1d00-8490-11ea-83eb-299209266716.png)

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/79939169-fba0d500-8490-11ea-82bc-680a33799a05.png)
你用下这个版本代码   我下午验证下这个最新版代码

**Comment by Gaoyongxian666** [comment]
好的，你指定的这个版本可以正常使用

**Comment by lingxiaoyi** [comment]
问题已解决 ,多谢反馈
